objects/Account.object
<CustomObject>
    <fields>
        <fullName>Default_Discount_Code__c</fullName>
        <description>for Apex badge</description>
        <label>Default Discount Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Apex badge exercise</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Products__c</fullName>
        <label>Products</label>
        <type>TextArea</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InvoiceControllerExtension.cls
public class InvoiceControllerExtension {

    private final Invoice__c invoice;
    private final Account account;
    public String products;
    

    public InvoiceControllerExtension(ApexPages.StandardController stdController) {
        this.invoice = (Invoice__c)stdController.getRecord();
        Opportunity opp = [SELECT Account.Name, Account.BillingCity,Account.BillingState,Account.BillingPostalCode,
                           Account.BillingCountry, Account.BillingStreet, Account.Default_Discount_Code__c FROM Opportunity WHERE Id = :invoice.Opportunity__c];
        account = opp.Account;
        List<OpportunityLineItem>  olines = [SELECT id, productcode from  OpportunityLineItem
                                             Where OpportunityId = :opp.Id];
            if (olines != null) {
                for (OpportunityLineItem ol : olines) {
                    invoice.Products__c = invoice.Products__c + ' , ' + ol.ProductCode;
                }
            } // end if 
    }
    
    
    public Account getAccount() { return account;}

    public String getGreeting() {
        return 'Hello World Order';
    }
}