objects/iOrder__c.object
<CustomObject>
    <fields>
        <fullName>Order_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Order External ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order_Status__c</fullName>
        <label>Order Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>iOrder</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>iOrders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/iOrderControllerExtension.cls
public class iOrderControllerExtension  
 {  
     private iOrder__c myOrder;  
     OrderShipInfo myOrderShipInfo;  
     OrderShipInfo.ShipInfo theShipInfo;    
     private ApexPages.StandardController controller {get; set;}  

   public iOrderControllerExtension(ApexPages.StandardController controller) {  
    //initialize the stanrdard controller  
    this.controller = controller;  
    this.myOrder = (iOrder__c)controller.getRecord();  
   }
   public void refreshOrderShipInfo()  
   {  
     myOrderShipInfo = new OrderShipInfo();  
     theShipInfo = myOrderShipInfo.getOrderShipInfo(this.myOrder.Order_External_ID__c);  

     myOrder.Order_Status__c = theShipInfo.status;    
     update myOrder;     
   }  
   public String getOrderStatus()  
   {  
    return theShipInfo.status;  
   }  
   public String getOrderComments()  
   {  
     return theShipInfo.comments;  
   }  
   public String getOrderOwner()  
   {  
     return theShipInfo.orderOwner;  
   }  
 }